export const JOURNEY_QUESTIONS = [
  { id: "value_peak", week: 1, theme: "我是誰", text: "哪一種時刻最讓你覺得『這就是我想過的人生』？", options: ["完成有挑戰的事情", "和重要的人深度相處", "自由探索新事物", "幫助別人變得更好"] },
  { id: "energy_source", week: 1, theme: "我是誰", text: "忙碌一天後，什麼最能幫你恢復能量？", options: ["獨處與安靜", "與熟悉的人聊天", "運動或外出", "學習或創作"] },
  { id: "decision_style", week: 1, theme: "我是誰", text: "面對重要選擇時，你通常先依靠什麼？", options: ["資料與邏輯", "直覺感受", "信任的人建議", "先試一小步再決定"] },
  { id: "natural_role", week: 1, theme: "我是誰", text: "在團體中，你最自然會成為哪一種角色？", options: ["帶方向的人", "整合協調的人", "提出創意的人", "穩定支持的人"] },
  { id: "flow_scene", week: 1, theme: "我是誰", text: "哪一類事情最容易讓你忘記時間？", options: ["解決複雜問題", "與人互動分享", "創作新的內容", "整理系統與細節"] },
  { id: "reward_preference", week: 1, theme: "我是誰", text: "哪一種成果最能讓你感到滿足？", options: ["看見明確數字成長", "得到他人的肯定", "感覺自己變得更強", "擁有更多自主時間"] },
  { id: "core_need", week: 1, theme: "我是誰", text: "現在的你最需要補充哪一種力量？", options: ["安全與穩定", "勇氣與行動", "方向與清晰", "支持與連結"] },
  { id: "life_picture", week: 2, theme: "我想去哪裡", text: "三年後理想的一天，最重要的畫面是什麼？", options: ["做喜歡且有價值的工作", "和家人有充足時間", "擁有健康與自由", "建立可持續的收入"] },
  { id: "priority_domain", week: 2, theme: "我想去哪裡", text: "未來90天，你最想推進哪一個領域？", options: ["工作或事業", "財務與收入", "健康與能量", "關係與家庭"] },
  { id: "work_future", week: 2, theme: "我想去哪裡", text: "你希望工作帶給你最重要的是什麼？", options: ["穩定保障", "成長舞台", "自主選擇", "影響他人"] },
  { id: "wealth_meaning", week: 2, theme: "我想去哪裡", text: "對你而言，財富最重要的意義是？", options: ["不必為生活擔心", "照顧重要的人", "選擇想做的事情", "創造更大的影響"] },
  { id: "relationship_ideal", week: 2, theme: "我想去哪裡", text: "理想關係中，你最重視什麼？", options: ["被理解與接納", "共同成長", "安全與承諾", "自由與信任"] },
  { id: "social_future", week: 2, theme: "我想去哪裡", text: "你希望身邊聚集哪一類人？", options: ["可靠穩定的人", "勇於冒險的人", "專業有深度的人", "溫暖願意合作的人"] },
  { id: "legacy", week: 2, theme: "我想去哪裡", text: "你最希望別人如何記得你？", options: ["完成過重要的事", "讓人感到被支持", "帶來新的觀點", "建立能持續的成果"] },
  { id: "pressure_response", week: 3, theme: "什麼阻止我", text: "壓力變大時，你最常出現哪種反應？", options: ["拖延或逃避", "過度控制細節", "急著做很多事", "把情緒悶在心裡"] },
  { id: "failure_story", week: 3, theme: "什麼阻止我", text: "事情不如預期時，你腦中最常出現哪句話？", options: ["我果然不夠好", "環境根本不允許", "再努力一點就好", "也許方向一開始就錯了"] },
  { id: "starting_barrier", week: 3, theme: "什麼阻止我", text: "開始重要任務前，最大的阻力通常是？", options: ["不知道第一步", "害怕做不好", "時間被切得太碎", "目標其實不夠重要"] },
  { id: "conflict_style", week: 3, theme: "什麼阻止我", text: "與人意見衝突時，你比較常怎麼做？", options: ["直接說清楚", "先退讓維持和平", "整理證據再溝通", "暫時離開避免升高"] },
  { id: "money_block", week: 3, theme: "什麼阻止我", text: "面對金錢機會時，你最容易卡在哪裡？", options: ["太保守錯過機會", "太衝動低估風險", "不敢談自己的價值", "缺少持續記錄與管理"] },
  { id: "visibility_block", week: 3, theme: "什麼阻止我", text: "需要被看見或表現時，你最擔心什麼？", options: ["被批評", "表現不夠專業", "承諾後做不到", "失去自己的風格"] },
  { id: "repeating_pattern", week: 3, theme: "什麼阻止我", text: "哪一種情況最常讓你的計畫中斷？", options: ["同時開太多目標", "別人的需求插隊", "前幾天太用力", "看不到短期成果"] },
  { id: "support_style", week: 4, theme: "我要如何前進", text: "什麼支持方式最能讓你持續行動？", options: ["清楚步驟與期限", "有人陪伴與回報", "看得見的進度", "保有彈性與選擇"] },
  { id: "best_time", week: 4, theme: "我要如何前進", text: "你通常在什麼時段最能完成重要任務？", options: ["清晨", "上午", "下午", "晚上"] },
  { id: "action_size", week: 4, theme: "我要如何前進", text: "哪種任務安排最適合你？", options: ["每天10分鐘", "每次25分鐘", "每週兩次深度投入", "依狀態彈性調整"] },
  { id: "learning_mode", week: 4, theme: "我要如何前進", text: "學習新能力時，你最有效的方式是？", options: ["先看完整架構", "直接操作練習", "跟著他人示範", "教別人來加深理解"] },
  { id: "accountability", week: 4, theme: "我要如何前進", text: "什麼最能提高你的完成率？", options: ["公開承諾", "固定提醒", "夥伴一起做", "完成後立即獎勵"] },
  { id: "setback_recovery", week: 4, theme: "我要如何前進", text: "計畫中斷後，什麼最能幫你重新開始？", options: ["把任務縮到最小", "重新確認原因", "換一種執行方式", "找人討論卡點"] },
  { id: "strength_choice", week: 4, theme: "我要如何前進", text: "接下來你最想刻意發揮哪項優勢？", options: ["創意與表達", "分析與策略", "連結與影響", "執行與管理"] },
  { id: "first_change", week: 4, theme: "我要如何前進", text: "如果只能改變一個習慣，你會先選哪個？", options: ["固定睡眠與起床", "每天推進主目標", "定期記錄與回顧", "減少無效承諾"] },
  { id: "commitment", week: 4, theme: "我要如何前進", text: "完成30天後，你願意給未來自己的承諾是？", options: ["先完成，再改善", "每天前進一點", "誠實面對自己的狀態", "選擇真正重要的事"] },
];

export const WEEKLY_REVIEW_ITEMS = [
  { id: "satisfaction", text: "本週整體滿意度", options: ["1", "2", "3", "4", "5"] },
  { id: "energy", text: "本週能量狀態", options: ["很低", "偏低", "普通", "不錯", "很好"] },
  { id: "progress", text: "最有進展的領域", options: ["事業", "財務", "健康", "關係", "自我成長"] },
  { id: "block", text: "最大的阻力", options: ["時間", "體力", "方向", "情緒", "外在事件"] },
  { id: "execution", text: "上週建議執行情況", options: ["幾乎沒有", "少部分", "約一半", "大部分", "全部"] },
  { id: "helpfulness", text: "建議對你有多大幫助", options: ["沒有", "偏低", "普通", "有幫助", "很有幫助"] },
  { id: "next_focus", text: "下週最想改善", options: ["行動力", "專注", "休息", "關係", "收入"] },
];
